# Einleitung

Diese Dokumention beschäftigt sich mit dem Filterentwurf eines Aktiven Biqaudfilters siehe Abbildung... sowie eines Aktiven Butterworth Tiefpassfilters dritter ordnung. Die dafür notwendige Schritte so wie der Implementierung wird in diesem Dokument vorgeführt und dessen Ergebnisse Diskutiert.

Der Biquadfilter zweiter Ordnung beinhaltet alle vier genängigen Filtertypen, welche im Labor gemessen und verglichen werden mit der Theorehtischen Schaltung.
Um ein Butterworth Tiefpassfilter zu erlangen wird die in der Abbildung.. gezeigte Schaltung um ein zusätzlichen Integrator mit einem invertierenden Verstärker ergänzt Siehe Abblidung...

TODO: BILD EINFÜGEN

Die zu entwerfende Aktive Tiefpassschaltung wird für drei unterschiedliche passband edge Frequenz untersucht:

|           | $f_0 = 159.155$  | $f_0 = 1591.55$  | $f_0 =15915.494$   |
|-----------|------------------|------------------|--------------------|
| $R_{com}$ |   $1k\Omega$     |   $1k\Omega$     |    $1k\Omega$      |
| $C_{com}$ |   $1\mu F$       |   $0.1 \mu F$    |   $0.01 \mu F$     |


Hier bei ergibt sich die passband edge Freqeunz aus der gleichung $\omega_0 = \frac{1}{R_{COM} \cdot C_{COM}}$ 

Die Spezfikation von Filtern beruht auf einem Toleranzschema wie in Abbildung... gezeigt. 

TODO:Bild Einfügen

Da der Biquadfilter durch eine Butterworthaproximation Entwurfen wurde so wie die Erweiterte schaltung ist im Durchlassbereich ein Glatterverlauf zu erwarten je nach Grundverstärkung entwerder um 0dB oder höher. 


Die Güte an der Biquad Schaltung lässt sich mit dem Widerstand .. Einstellen. Die Güte gibt an wie sehr der Frequenzgang sich um die eingestellte Grenzfreqeunz $f_0 = \frac{\omega_0}{2 \cdot \pi} $ sich ändert 

TODO: Das noch genauer Beschreiben
