# Biquad Filterschaltung

<!-- [Biquadschaltung](../images/Biquadschaltung.png){#fig-map}

Die in **Abbildung 1**  gezeigt schaltung wird in diesem Abschnit der Dokumentation behandelt. Es handelt sich hierbei um ein Universellen Biquad Filter welcher 4 Filter Typen in einem Realisiert. Eine wichtiger Parameter von Filtern ist die Güte dies lässt sich mit dem Widerstand R5 einstellen. Bei steigender güte sinkt je nach Filter Type entweder die Bandbreite z.B. beim Notchfilter (bandsperre) oder beim Bandpass und beim Tiefpassfilter bzw Hochapssfilter die Übergangsfrequenz sprich die breite.-->

```{python}
import matplotlib.pyplot as plt
import numpy as np
from ltspice import Ltspice
import pandas as pd
```

```{python}
# Messwerte Tiefpassfilter mit Q1
dfLPFQ1 = pd.read_csv("Data/Messung1_LPF.csv", sep=',')
fTPQ1 = np.array(dfLPFQ1['Frequency [Hz]'])
gainTPQ1=np.array(dfLPFQ1[' Amplitude [dB]'])
phaseTPQ1 = np.array(dfLPFQ1[' Phase [deg]'])

# Messwerte Tiefpassfilter mit Q10
dfLPFQ10 = pd.read_csv("Data/Messung2_LPF.csv",sep=',')
fTPQ10 = np.array(dfLPFQ10['Frequency [Hz]'])
gainTPQ10=np.array(dfLPFQ10[' Amplitude [dB]'])
phaseTPQ10 = np.array(dfLPFQ10[' Phase [deg]'])

# Messwerte Hochpassfilter mit Q1
dfHPFQ1 = pd.read_csv("Data/Messung1_HPF.csv",sep=',')
fHPFQ1 = np.array(dfHPFQ1['Frequency [Hz]'])
gainHPFQ1=np.array(dfHPFQ1[' Amplitude [dB]'])
phaseHPFQ1 = np.array(dfHPFQ1[' Phase [deg]'])

# Messwerte Hochpassfilter mit Q10
dfHPFQ10 = pd.read_csv("Data/Messung2_HPF.csv",sep=',')
fHPFQ10 = np.array(dfHPFQ10['Frequency [Hz]'])
gainHPFQ10=np.array(dfHPFQ10[' Amplitude [dB]'])
phaseHPFQ10 = np.array(dfHPFQ10[' Phase [deg]'])

# Messwerte Bandpassfilter mit Q1
dfBPFQ1 = pd.read_csv("Data/Messung1_BPF.csv",sep=',')
fBPFQ1 = np.array(dfBPFQ1['Frequency [Hz]'])
gainBPFQ1=np.array(dfBPFQ1[' Amplitude [dB]'])
phaseBPFQ1 = np.array(dfBPFQ1[' Phase [deg]'])

# Messwerte Bandpassfilter mit Q10
dfBPFQ10 = pd.read_csv("Data/Messung2_BPF.csv",sep=',')
fBPFQ10 = np.array(dfBPFQ10['Frequency [Hz]'])
gainBPFQ10=np.array(dfBPFQ10[' Amplitude [dB]'])
phaseBPFQ10 = np.array(dfBPFQ10[' Phase [deg]'])

# Messwerte Bandsperre mit Q1
dfBSFQ1 = pd.read_csv("Data/Messung1_BSF.csv",sep=',')
fBSFQ1 = np.array(dfBSFQ1['Frequency [Hz]'])
gainBSFQ1=np.array(dfBSFQ1[' Amplitude [dB]'])
phaseBSFQ1 = np.array(dfBSFQ1[' Phase [deg]'])

# Messwerte Bandsperre mit Q10
dfBSFQ10 = pd.read_csv("Data/Messung2_BSF.csv",sep=',')
fBSFQ10 = np.array(dfBSFQ10['Frequency [Hz]'])
gainBSFQ10=np.array(dfBSFQ10[' Amplitude [dB]'])
phaseBSFQ10 = np.array(dfBSFQ10[' Phase [deg]'])
```

```{python} 
# -----------------------------------Einladen der Simulations Werte -----------------------------------------
# Werte für die Tiefpassfilter mit güte 1
filepath1 = './spice_kicad/FSQ1.raw'
l1 = Ltspice(filepath1)
l1.parse() # Data loading sequence. It may take few minutes for huge file.

f1 = l1.get_frequency()
Vbpf1 = l1.get_data('v(bpf)')
Vbsf1 = l1.get_data('v(bsf)')
Vhpf1 = l1.get_data('v(hpf)')
Vlpf1 = l1.get_data('v(lpf)')

# Werte für die Tiefpassfilter mit güte 10

filepath10 = './spice_kicad/FSQ10.raw'
l2 = Ltspice(filepath10)
l2.parse()

f2 = l2.get_frequency()
Vbpf10 = l2.get_data('v(bpf)')
Vbsf10 = l2.get_data('v(bsf)')
Vhpf10 = l2.get_data('v(hpf)')  # https://www.ti.com/lit/ds/symlink tl082-n.pdf
Vlpf10 = l2.get_data('v(lpf)')
```

# Vergleich der Messwerte mit den Simulationswerten


## Tiefpassfilter

```{python}
plt.figure("Amplitudengang des Tiefpass filters")
plt.title("Amplitudengang des Tiefpassfilters")
plt.plot(f1,20*np.log10(abs(Vlpf1)),".:",label="Q1 TP Simulation")
plt.plot(f2,20*np.log10(abs(Vlpf10)),".:",label="Q10 TP Simulation")
plt.plot(fTPQ1,gainTPQ1,label='Tiefpassfilter gemessen Q1')
plt.plot(fTPQ10,gainTPQ10,label='Tiefpassfilter gemessen Q10')
plt.xscale('log')
plt.grid()
plt.legend()
plt.show()
```

# Vergleich der Messwerte mit den Simulationswerten
Vergleicht man die in Abbildung 2 abgebildeten Amplitudengände des Tiefpassfilters, erkennt man ab ca. 10kHz bei Güte 1, bzw. 50kHz bei Güte 10, Abweichungen der gemessenen zu der theoretischen Simulation aus KiCad. Bei höheren Frequenzen kommen mehrerere Faktoren zusammen, die das ideale Verhalten beeinträchtigen:
    - Parasitäre Effekte: Bei den theoretischen Modellen werden   die Streukapazitäten und -induktivitäten, die in den realen Bauelementen vorhanden sind, nicht berücksichtigt. Diese parasiäten Effekten werden aber bei hohen Frequenzen zunehmend relevant und könnten einer der Faktoren der Abweichungen sein.
    - Frequenzabhängiges Bauteilverhalten: Mit steigender Frequenz sinkt der Widerstand vom Kondensator. Bei steigender Frequenz ändert sich damit das Spannungsverhältnis, was zu Abweichungen führt.
    - Nicht-idealen Eigenschaften eines OpAmps: Zum Beispiel die endliche Verstärkung, Offsetspannungen und Eingangs-Bias-Ströme, haben potenziell die größten Auswirkungen auf die Leistung eines Biquad-Filters. Diese Fehlerquellen können zu Verzerrungen, Verlust der Genauigkeit und Fehlern in der Frequenzgangkurve führen. Besonders bei präzisen Filtern und Anwendungen, die eine exakte Frequenzantwort erfordern (z. B. Audio- oder Kommunikationssysteme), müssen diese nicht-idealen Effekte berücksichtigt und in der Schaltungs- oder Filtergestaltung ausgeglichen werden.Um diese Probleme zu minimieren, wird in der Praxis häufig Präzisions-OpAmps verwendet, die geringe Fehlerquellen aufweise

## Dokumentierte Abweichungen
In den Versuchsergebnissen wurden bereits erhebliche Abweichungen zwischen berechneten und gemessenen Werten dokumentiert:
    - Die Abweichungen der Grenzfrequenz beträgt 1,57kHz bzw. 15,8%
    - Die absolute Abweichung zwischen ReÜberschwingen im Übergangsbereich: Im Bereich um 1000 Hz zeigt insbesondere die Q10-Simulation (orange) ein deutliches Überschwingen, das beim Q10-Wert mit seiner steileren Flankensteilheit zu erwarten ist
    
## Spezielle Effekte bei hohen Frequenzen
Bei Frequenzen deutlich über der Grenzfrequenz kommen zusätzliche Effekte zum Tragen:
    - Die Filtersteilheit realer Filter kann von den theoretischen abweichen.
    - Belastungseffekte durch nachfolgeden Stufen verändern die Filtercharakteristik. Wenn beispielsweise ein Hochpass an einen Tiefpass angeschlossen wird, verändert sich das Übertragungsverhalten durch die Parallelschaltung.
Diese Beobachtungen decken sich mit der Grafik, die deutliche Unterschiede zwischen Suimulation und Messung im Breich ab 10kHz zeigt, insbesondere bei der Tiefe der Dämpfungskurve und dem erneuten Anstieg bei sehr hohen Frequenzen.

```{python}
plt.figure("Phasengang des Tiefpass filters")
plt.title("Phasengang des Tiefpass filters")
plt.plot(f1,np.degrees(np.angle(Vlpf1)),".:",label="Q1 TP Simulation")
plt.plot(f2,np.degrees(np.angle(Vlpf10)),".:",label="Q10 TP Simulation")
plt.plot(fTPQ1,phaseTPQ1,".:",label='Tiefpassfilter gemessen Q1')
plt.plot(fTPQ10,phaseTPQ10,".:",label='Tiefpassfilter gemessen Q10')
plt.xscale('log')
plt.grid()
plt.legend()
plt.show()
```

## Hochpassfilter
```{python}
plt.figure("Amplitudengang des Hochpassfilters")
plt.title("Amplitudengang des Hochpassfilters")
plt.plot(f1,20*np.log10(abs(Vhpf1)),".:",label="Q1 HP Simulation")
plt.plot(f2,20*np.log10(abs(Vhpf10)),".:",label="Q10 HP Simulation")
plt.plot(fHPFQ1,gainHPFQ1,label='Hochpassfilter gemessen Q1')
plt.plot(fHPFQ10,gainHPFQ10,label='Hochpassfilter gemessen Q10')
plt.xscale('log')
plt.grid()
plt.legend()
plt.show()
```

# Vergleich der Messwerte mit den Simulationswerten
Bei den Amplitudengänge des Hochpassfilters aus Abbildung 4 gibt es ähnliche Gründe für die Abweichungen wie beim Tiefpassfilter, aber mit dem Unterschied, dass sie hier bei sehr niedrigen Frequenzen und ebenfalls sehr niedrigen dB-Werten auftreten. Dabei gibt es mehrere Faktoren, die diese Abweichungen erklären:
    - Reales Verhalten der Bauelemente: Bei extrem niedrigen Frequenzen verhalten sich Kondensatoren nicht mehr ideal. Während ein idealer Kondensator bei sehr niedrigen Frequenzen wie eine vollständige Sperre wirken sollte, haben reale Kondensatoren Leckströme, die einen gewissen Signaldurchlass ermöglichen
    - Parasitäre Effekte: Reale Bauteile besitzen Parallelwiderstände, die besonders bei niedrigen Frequenzen zum Tragen kommen. Bei Kondensatoren führt dies dazu, dass sie nicht mehr als perfekte Isolatoren wirken
    - Rauscheffekte und Messgenauigkeit: Bei sehr niedirgen dB-Werten (unter -80dB) stoßen Messgeräte an ihre Grenzen, was zu unregelmäßigen Messergebnissen führen kann.

## Dokumentierte Abweichungen
Im angezeigten Amplitudengang des Hochpassfilters sind mehrere charakteristische Abweichungen erkennbar:
    - Starker Einbruch bei Q1-Messung: Die rote Linie (gemessener Q1-Hochpass) zeigt bei etwa 20-30 Hz einen markanten Einbruch auf fast -110 dB, der in der Simulation nicht vorkommt. Dies deutet auf resonante Effekte zwischen den realen Bauteilen hin
    - Flacherer Anstieg bei niedrigen Frequenzen: Der Anstieg der gemessenen Kurven (rot und grün) ist bei sehr niedrigen Frequenzen weniger steil als bei den simulierten Kurven, was auf die nicht-idealen Eigenschaften der Bauelemente zurückzuführen ist
    - Überschwingen im Übergangsbereich: Im Bereich um 1000 Hz zeigt insbesondere die Q10-Simulation (orange) ein deutliches Überschwingen, das beim Q10-Wert mit seiner steileren Flankensteilheit zu erwarten ist

```{python}
plt.figure("Phasengang des Hochpassfilters")
plt.title("Phasengang des Hochpassfilters")
plt.plot(f1,np.degrees(np.angle(Vhpf1)),".:",label="Q1 HP Simulation")
plt.plot(f2,np.degrees(np.angle(Vhpf10)),".:",label="Q10 HP Simulation")
plt.plot(fHPFQ1,phaseHPFQ1,label='Hochpassfilter gemessen Q1')
plt.plot(fHPFQ10,phaseHPFQ10,label='Hochpassfilter gemessen Q10')
plt.xscale('log')
plt.grid()
plt.legend()
plt.show()
```

## Bandpassfilter
```{python}
plt.figure("Amplitudengang des Bandpassfilters")
plt.title("Amplitudengang des Bandpassfilters")
plt.plot(f1,20*np.log10(abs(Vbpf1)),".:",label="https://www.ti.com/lit/ds/symlink/tl082-n.pdfQ1 BPF Simulation")
plt.plot(f2,20*np.log10(abs(Vbpf10)),".:",label="Q10 BPF Simulation")
plt.plot(fBPFQ1,gainBPFQ1,label='Bandpassfilter gemessen Q1')
plt.plot(fBPFQ10,gainBPFQ10,label='Bandpassfilter gemessen Q10')
plt.xscale('log')
plt.grid()
plt.legend()
plt.show()
```

```{python}
plt.figure("Phasengang des Bandpassfilters")
plt.title("Phasengang des Bandpassfilters")
plt.plot(f1,np.degrees(np.angle(Vbpf1)),".:",label="Q1 BPF Simulation")
plt.plot(f2,np.degrees(np.angle(Vbpf10)),".:",label="Q10 BPF Simulation")
plt.plot(fBPFQ1,phaseBPFQ1,label='Bandpassfilter gemessen Q1')
plt.plot(fBPFQ10,phaseBPFQ10,label='Bandpassfilter gemessen Q10')
plt.xscale('log')
plt.grid()
plt.legend()
plt.show()
```

## Bandstopfilter

```{python}
plt.figure("Amplitudengang des Bandstopfilters")
plt.title("Amplitudengang des Bandstopfilters")
plt.plot(f1,20*np.log10(abs(Vbsf1)),".:",label="Q1 BSF Simulation")
plt.plot(f2,20*np.log10(abs(Vbsf10)),".:",label="Q10 BSF Simulation")
plt.plot(fBSFQ1,gainBSFQ1,label='Bandstopfilter gemessen Q1')
plt.plot(fBSFQ10,gainBSFQ10,label='Bandstopfilter gemessen Q10')
plt.xscale('log')
plt.grid()
plt.legend()
plt.show()
```

```{python}
plt.figure("Phasengang des Bandstopfilters")
plt.title("Phasengang des Bandstopfilters")
plt.plot(f1,np.degrees(np.angle(Vbsf1)),".:",label="Q1 BSF Simulation")
plt.plot(f2,np.degrees(np.angle(Vbsf10)),".:",label="Q10 BSF Simulation")
plt.plot(fBSFQ1,phaseBSFQ1,label='Bandstopfilter gemessen Q1')
plt.plot(fBSFQ10,phaseBSFQ10,label='Bandstopfilter gemessen Q10')
plt.xscale('log')
plt.grid()
plt.legend()
plt.show()
```
Die Güte hat ein Problem in der Rellen Schaltung

# Butterworthfilter 

```{python} 
# Einladen der Messwerte
# ----- Butter1uF ------------- 
Butter1uF = pd.read_csv("./Data/4.5_1uF_Data.csv",sep=',')
fButter1uf = np.array(Butter1uF['Frequency [Hz]'])
gain1uf=np.array(Butter1uF[' Amplitude [dB]'])
phase1uf = np.array(Butter1uF[' Phase [deg]'])

# ------Butter 0.1 uF ---------- 
Butter01uF = pd.read_csv("./Data/4.5_0.1uF_Data.csv",sep=',')
fButter01uf = np.array(Butter01uF['Frequency [Hz]'])
gain01uf=np.array(Butter01uF[' Amplitude [dB]'])
phase01uf = np.array(Butter01uF[' Phase [deg]'])

# ------Butter 0.01uF -------- f0 = 
Butter001uF = pd.read_csv("./Data/4.5_0.01uf_Data.csv",sep=',')
fButter001uf = np.array(Butter001uF['Frequency [Hz]'])
gain001uf=np.array(Butter001uF[' Amplitude [dB]'])
phase001uf = np.array(Butter001uF[' Phase [deg]'])

```
```{python}
# Einladen der Simuliertenwerte

# Werte aus der Simulation mit 1 uF  
filepath3 = './spice_kicad/Butterworththirdorder1u.raw'
l3 = Ltspice(filepath3)
l3.parse() # Data loading sequence. It may take few minutes for huge file.

f3 = l3.get_frequency()
Vbpf3 = l3.get_data('v(bpf)')
Vbsf3 = l3.get_data('v(bsf)')
Vhpf3 = l3.get_data('v(hpf)')
Vlpf3 = l3.get_data('v(lpf)')
Vout1u  = l3.get_data('v(Vout)') 

# Werte aus der Simulation mit 0.1 uF

filepath4 = './spice_kicad/Butterworththirdorder0.1u.raw'
l4 = Ltspice(filepath4)
l4.parse() # Data loading sequence. It may take few minutes for huge file.

f4 = l4.get_frequency()
Vbpf4 = l4.get_data('v(bpf)')
Vbsf4 = l4.get_data('v(bsf)')
Vhpf4 = l4.get_data('v(hpf)')
Vlpf4 = l4.get_data('v(lpf)')
Vout01u  = l4.get_data('v(Vout)') 

# Werte aus der Simulation mit 0.01 uF

filepath5 = './spice_kicad/Butterworththirdorder0.01u.raw'
l5 = Ltspice(filepath5)
l5.parse() # Data loading sequence. It may take few minutes for huge file.

f5 = l5.get_frequency()
Vbpf5 = l5.get_data('v(bpf)')
Vbsf5 = l5.get_data('v(bsf)')
Vhpf5 = l5.get_data('v(hpf)')
Vlpf5 = l5.get_data('v(lpf)')
Vout001u  = l5.get_data('v(Vout)') 

```
# Plot und Vergleich:

## Butterworth 1uF
```{python}
plt.figure("Amplitudengang Butterworth TP 1uF")
plt.title("Amplitudengang Butterworth 1uF")
plt.plot(f3,20*np.log10(abs(Vout1u)),".:",label="Simulation")
plt.plot(fButter1uf,gain1uf,label='Tiefpassfilter gemessen')
plt.xscale('log')
plt.grid()
plt.legend()
plt.show()
```

```{python}
plt.figure("Phasengang Butterworth TP 1uF")
plt.title("Phasengang Butterworth 1uF")
plt.plot(f3,np.degrees(np.angle(Vout1u)),".:",label="Simulation")
plt.plot(fButter1uf,phase1uf,label='Butterworth gemessen')
plt.xscale('log')
plt.grid()
plt.legend()
plt.show()
```
## Butterworthfilter 0.1uF
```{python}
plt.figure("Amplitudengang Butterworth TP 0.1uF")
plt.title("Amplitudengang Butterworth 0.1uF")
plt.plot(f4,20*np.log10(abs(Vout01u)),".:",label="Simulation")
plt.plot(fButter01uf,gain01uf,label='Tiefpassfilter gemessen')
plt.xscale('log')
plt.grid()
plt.legend()
plt.show()
```

```{python}
plt.figure("Phasengang Butterworth TP 0.1uF")
plt.title("Phasengang Butterworth 0.1uF")
plt.plot(f4,np.degrees(np.angle(Vout01u)),".:",label="Simulation")
plt.plot(fButter01uf,phase01uf,label='Butterworth gemessen')
plt.xscale('log')
plt.grid()
plt.legend()
plt.show()
```
# Butterworthfilter 0.01uF

```{python}
plt.figure("Amplitudengang Butterworth TP 0.01uF")
plt.title("Amplitudengang Butterworth 0.01uF")
plt.plot(f5,20*np.log10(abs(Vout001u)),".:",label="Simulation")
plt.plot(fButter001uf,gain001uf,label='Tiefpassfilter gemessen')
plt.xscale('log')
plt.grid()
plt.legend()
plt.show()
```

```{python}
plt.figure("Phasengang Butterworth TP 0.01uF")
plt.title("Phasengang Butterworth 0.01uF")
plt.plot(f5,np.degrees(np.angle(Vout001u)),".:",label="Simulation")
plt.plot(fButter001uf,phase001uf,label='Butterworth gemessen')
plt.xscale('log')
plt.grid()
plt.legend()
plt.show()
```

# Grenzfreqeunz Funktion für unterschiedliche Kapazitätswerte bei gleichbleibendem Widerstand
```{python}
Rcom = 1e3
Ccom = np.linspace(1e-12,1e-6,10000)

f0 = (1/(Rcom*Ccom))*(1/(2*np.pi))
plt.figure("Theorehtische Grenzfreqeuenz in Abhängigkeit von C")
plt.title("Theorehtische Grenzfreqeuenz in Abhängigkeit von C")
plt.plot(Ccom,f0)
plt.grid()
plt.legend()
plt.ylabel("Freqeuenz in Hz")
plt.xlabel("Kapazität in Farad")
plt.xscale('log')
```

[@baker2010]
